name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Clean and build
        run: |
          cd src/WorkerAssistant.Client
          rm -rf bin obj publish
          dotnet publish -c Release -o ./publish
          
      - name: Verify files
        run: |
          cd src/WorkerAssistant.Client/publish/wwwroot
          echo "Files in wwwroot:"
          ls -la
          if [ ! -d "_framework" ]; then
            echo "❌ Framework folder missing!"
            exit 1
          fi
          
      - name: Deploy to Azure
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_BUSH_07D87F803 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "src/WorkerAssistant.Client/publish/wwwroot"  # Directory containing wwwroot
          output_location: "wwwroot"  # The static files folder
          api_location: ""
          skip_app_build: true
          
      - name: Verify deployment
        run: |
          DEPLOY_URL="${{ steps.deploy.outputs.static_web_app_url }}"
          echo "Testing deployment URLs:"
          
          # Test WASM file
          WASM_URL="$DEPLOY_URL/_framework/blazor.webassembly.js"
          WASM_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$WASM_URL")
          echo "WASM: $WASM_URL → $WASM_STATUS"
          
          if [ "$WASM_STATUS" -ne 200 ]; then
            echo "❌ Deployment failed!"
            exit 1
          fi
          echo "✅ Deployment successful"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_BUSH_07D87F803 }}
          action: "close"
