name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Publish Blazor Project
        run: |
          cd src/WorkerAssistant.Client
          dotnet publish -c Release -o ./publish
          
          # Verify files in wwwroot
          echo "Files in wwwroot:"
          ls -la ./publish/wwwroot
          
          # Confirm critical files exist
          if [ ! -f "./publish/wwwroot/WorkerAssistant.Client.styles.css" ]; then
            echo "❌ CSS file missing!"
            exit 1
          fi
          
          if [ ! -f "./publish/wwwroot/_framework/blazor.webassembly.js" ]; then
            echo "❌ Blazor WASM file missing!"
            exit 1
          fi

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_BUSH_07D87F803 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "src/WorkerAssistant.Client/publish/wwwroot" 
          api_location: ""
          output_location: "" 

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_BUSH_07D87F803 }}
          action: "close"
